table AMZN_data_1999_2022
	lineageTag: 82f7e5c5-98a0-4c3c-afcc-766fa90e0390

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 342a05cb-226f-487a-aade-7fa18474e44e
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 90a85678-6d2f-4090-b0d0-4e9346d49c76
			defaultHierarchy: LocalDateTable_a8ba122f-c8fa-47f7-9ca4-b2c46fe09a60.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Open
		dataType: double
		lineageTag: 9301367f-a309-459e-aa82-d4c9b19077e0
		summarizeBy: sum
		sourceColumn: Open

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column High
		dataType: double
		lineageTag: 9bfdb8d5-b22d-42aa-9010-2a0f594bab88
		summarizeBy: sum
		sourceColumn: High

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Low
		dataType: double
		lineageTag: f81f3099-d405-48c6-8f7a-5286c694ed2e
		summarizeBy: sum
		sourceColumn: Low

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Close
		dataType: double
		lineageTag: 107cfc2d-2e88-4352-b9ec-4cafaa5fdc4c
		summarizeBy: sum
		sourceColumn: Close

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Adj Close'
		dataType: double
		lineageTag: e79741b1-f8ec-4c74-b880-64c69b118579
		summarizeBy: sum
		sourceColumn: Adj Close

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Volume
		dataType: int64
		formatString: 0
		lineageTag: cd2a4cb1-52a3-4fb6-a6ed-9975c2f5b97a
		summarizeBy: sum
		sourceColumn: Volume

		annotation SummarizationSetBy = Automatic

	partition AMZN_data_1999_2022 = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\havef\OneDrive - onionbi.co.kr\_ONIONBI\07 Git_Repository\pbi\AMZN_data_1999_2022.csv"),[Delimiter=",", Columns=7, Encoding=949, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"Open", type number}, {"High", type number}, {"Low", type number}, {"Close", type number}, {"Adj Close", type number}, {"Volume", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

