{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Data\",\"부서및직무정보\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.138.1452.0 (24.11)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "ko-KR",
    "cultures": [
      {
        "name": "ko-KR",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "0d009aa9-3db8-46ff-a453-4d1a6956d1a6",
        "fromColumn": "입사일자",
        "fromTable": "Data",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_29b8f329-5586-4fd2-93c4-4421ebd893a4"
      },
      {
        "name": "953255f2-d5b5-4bcb-a56a-6267ef90a8ee",
        "fromColumn": "퇴사일자",
        "fromTable": "Data",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_f7ac4415-0767-40ca-b482-5f6fde436925"
      },
      {
        "name": "2a719791-a684-413e-97fc-c82e88393615",
        "fromColumn": "직무ID",
        "fromTable": "Data",
        "toColumn": "직무ID",
        "toTable": "부서및직무정보"
      }
    ],
    "sourceQueryCulture": "ko-KR",
    "tables": [
      {
        "name": "Data",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "탐색"
          }
        ],
        "columns": [
          {
            "name": "직원ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "eb948022-17db-4c2e-8f3b-73aea42ad138",
            "sourceColumn": "직원ID",
            "summarizeBy": "count"
          },
          {
            "name": "근무지역",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ebbb453b-076c-450c-aa5f-eaf8fd05a9c4",
            "sourceColumn": "근무지역",
            "summarizeBy": "none"
          },
          {
            "name": "직원이름",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "024239e0-0bb9-4b48-891e-76f6d9faf246",
            "sourceColumn": "직원이름",
            "summarizeBy": "none"
          },
          {
            "name": "입사일자",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "6f630476-3bfa-4681-ab23-7c3868211460",
            "sourceColumn": "입사일자",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "변형",
                "defaultHierarchy": {
                  "hierarchy": "날짜 계층",
                  "table": "LocalDateTable_29b8f329-5586-4fd2-93c4-4421ebd893a4"
                },
                "isDefault": true,
                "relationship": "0d009aa9-3db8-46ff-a453-4d1a6956d1a6"
              }
            ]
          },
          {
            "name": "퇴사일자",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "dbf6ffcf-5026-442e-af3a-1e848bdc23c3",
            "sourceColumn": "퇴사일자",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "변형",
                "defaultHierarchy": {
                  "hierarchy": "날짜 계층",
                  "table": "LocalDateTable_f7ac4415-0767-40ca-b482-5f6fde436925"
                },
                "isDefault": true,
                "relationship": "953255f2-d5b5-4bcb-a56a-6267ef90a8ee"
              }
            ]
          },
          {
            "name": "성별",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "970ea587-2e51-4746-96db-d07e903b34d3",
            "sourceColumn": "성별",
            "summarizeBy": "none"
          },
          {
            "name": "고용상태",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ff01b376-32ea-4c48-aba7-2cf623b7050e",
            "sourceColumn": "고용상태",
            "summarizeBy": "none"
          },
          {
            "name": "부서ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d36be8d7-a136-4713-a5b2-2fde2711e69b",
            "sourceColumn": "부서ID",
            "summarizeBy": "count"
          },
          {
            "name": "직무ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c37a7c17-0adb-4ddd-962b-35dcf143324c",
            "sourceColumn": "직무ID",
            "summarizeBy": "none"
          },
          {
            "name": "매니저ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cac79ce4-c6c7-4300-9300-2ac63a13a760",
            "sourceColumn": "매니저ID",
            "summarizeBy": "count"
          },
          {
            "name": "매니저명",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f204eb62-aa5b-45f8-ad22-7cfee310bc7b",
            "sourceColumn": "매니저명",
            "summarizeBy": "none"
          },
          {
            "name": "생년월일",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "55ddb0ee-a24c-457d-b2fe-1fcc48c02800",
            "sourceColumn": "생년월일",
            "summarizeBy": "none"
          },
          {
            "name": "퇴직사유",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c6ac2e4c-38ef-48e4-8e66-7c98d9abb2a1",
            "sourceColumn": "퇴직사유",
            "summarizeBy": "none"
          },
          {
            "name": "채용루트",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "43b8bde0-92af-440a-890a-e4d865f9df9c",
            "sourceColumn": "채용루트",
            "summarizeBy": "none"
          },
          {
            "name": "성취도",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9f427341-aedc-4d70-b84c-b0f02b7d96f1",
            "sourceColumn": "성취도",
            "summarizeBy": "sum"
          },
          {
            "name": "급여수준",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "611367a8-7281-4df9-89cc-1fe0c7884f92",
            "sourceColumn": "급여수준",
            "summarizeBy": "sum"
          },
          {
            "name": "몰입도",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "bdbdbb9d-064c-454b-ad7c-f1152b388bab",
            "sourceColumn": "몰입도",
            "summarizeBy": "sum"
          },
          {
            "name": "만족도",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3fdfc8ce-fe71-427d-a743-c9cac2191f06",
            "sourceColumn": "만족도",
            "summarizeBy": "sum"
          },
          {
            "name": "프로젝트참여건수",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c631d65e-03e9-4dab-91be-21bd741708e6",
            "sourceColumn": "프로젝트참여건수",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "d5b79391-ca20-46fa-b32e-2110801663aa",
        "measures": [
          {
            "name": "noOfEmp",
            "expression": "Distinctcount('Data'[직원ID])",
            "formatString": "#,0",
            "lineageTag": "2a6a8ccf-46b8-4c13-9b02-503be40f4ba2"
          }
        ],
        "partitions": [
          {
            "name": "Data",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    원본 = Excel.Workbook(File.Contents(\"C:\\Users\\havef\\OneDrive - onionbi.co.kr\\_ONIONBI\\02 Training\\01 Personal\\02 Offline\\01 Group\\01_기본반\\02 수업자료_v3.0\\01_직원현황데이터_샘플.xlsx\"), null, true),",
                "    Data_Sheet = 원본{[Item=\"Data\",Kind=\"Sheet\"]}[Data],",
                "    #\"승격된 헤더\" = Table.PromoteHeaders(Data_Sheet, [PromoteAllScalars=true]),",
                "    #\"변경된 유형\" = Table.TransformColumnTypes(#\"승격된 헤더\",{{\"직원ID\", Int64.Type}, {\"근무지역\", type text}, {\"직원이름\", type text}, {\"입사일자\", type date}, {\"퇴사일자\", type date}, {\"성별\", type text}, {\"고용상태\", type text}, {\"부서ID\", Int64.Type}, {\"직무ID\", Int64.Type}, {\"매니저ID\", Int64.Type}, {\"매니저명\", type text}, {\"생년월일\", type text}, {\"퇴직사유\", type text}, {\"채용루트\", type text}, {\"성취도\", Int64.Type}, {\"급여수준\", type number}, {\"몰입도\", type number}, {\"만족도\", Int64.Type}, {\"프로젝트참여건수\", Int64.Type}}),",
                "    #\"추출된 구분 기호 앞 텍스트\" = Table.TransformColumns(#\"변경된 유형\", {{\"직원이름\", each Text.BeforeDelimiter(_, \",\"), type text}}),",
                "    #\"필터링된 행\" = Table.SelectRows(#\"추출된 구분 기호 앞 텍스트\", each ([성별] = \"F\")),",
                "    #\"추출된 처음 문자\" = Table.TransformColumns(#\"필터링된 행\", {{\"근무지역\", each Text.Start(_, 2), type text}})",
                "in",
                "    #\"추출된 처음 문자\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_2a54c273-1a55-4ca7-b74c-f05ad0eb0096",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "c46712c3-8144-44ca-9062-ec0a61424fdc",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "연도",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "ba04ffda-5183-41ff-bd54-c7c8e4b13d0a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "b6915834-fa84-4168-a25e-437ee834ca5e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "월",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "bffb37de-6c86-453d-9953-c7917da4ebca",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "6500c580-9cb5-445c-a915-ff8db2e11045",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "분기",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"분기 \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "ebf998e0-263f-4b1d-a10f-d61bbcec4b6c",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "일",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "62da8070-d453-4e09-acd7-612597b5eb43",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "날짜 계층",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "연도",
                "column": "연도",
                "lineageTag": "b67f5cd2-cfb9-444c-9d4d-eadb24905561",
                "ordinal": 0
              },
              {
                "name": "분기",
                "column": "분기",
                "lineageTag": "024ac7b0-f6d7-48dd-b559-18161f3c7d42",
                "ordinal": 1
              },
              {
                "name": "월",
                "column": "월",
                "lineageTag": "c60c099b-1646-4ebb-99e0-438875c31299",
                "ordinal": 2
              },
              {
                "name": "일",
                "column": "일",
                "lineageTag": "d75f9577-a395-4722-8c48-2de161dd3266",
                "ordinal": 3
              }
            ],
            "lineageTag": "15151fe2-1d0e-45b2-bc1f-031b4dec17d3"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "c118ede3-e458-4164-946b-f07a4268ac76",
        "partitions": [
          {
            "name": "DateTableTemplate_2a54c273-1a55-4ca7-b74c-f05ad0eb0096",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_29b8f329-5586-4fd2-93c4-4421ebd893a4",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "a2ef5474-d9d3-40cc-96b8-d7e272c2790b",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "연도",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "3b99bb72-9777-4be1-a475-771982f732ef",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "80104cba-852e-4c46-a6b5-f82f38d9985b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "월",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "73fa8dae-3409-4d59-98be-08dcfa9d86fb",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "4db80376-aadf-4e93-92cc-0a4a91cbcbb3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "분기",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"분기 \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "11038446-8694-4c40-8908-ccb20aec2570",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "일",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "7bf19771-35cf-44b6-9b84-f621270e397b",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "날짜 계층",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "연도",
                "column": "연도",
                "lineageTag": "b5378919-0019-4d87-8919-75120ef82bf3",
                "ordinal": 0
              },
              {
                "name": "분기",
                "column": "분기",
                "lineageTag": "75bfdd6e-ffd5-49ea-8d13-87730b33fdd0",
                "ordinal": 1
              },
              {
                "name": "월",
                "column": "월",
                "lineageTag": "5ac79194-5612-4b56-93f7-c9db68b64b71",
                "ordinal": 2
              },
              {
                "name": "일",
                "column": "일",
                "lineageTag": "4a3516d4-7321-4261-8c1e-36bff6cc07b9",
                "ordinal": 3
              }
            ],
            "lineageTag": "ceb58930-cc94-4078-8ae3-41d189b7d83b"
          }
        ],
        "isHidden": true,
        "lineageTag": "599bd2d1-44f6-4c7b-bdd3-248a433794e2",
        "partitions": [
          {
            "name": "LocalDateTable_29b8f329-5586-4fd2-93c4-4421ebd893a4",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Data'[입사일자])), 1, 1), Date(Year(MAX('Data'[입사일자])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_f7ac4415-0767-40ca-b482-5f6fde436925",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "eb967567-94dc-4355-ad7b-24603c4a8d36",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "연도",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "f8adff5e-563c-4d77-a832-5567f3ddb1ff",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "9e828bd5-5398-4131-8359-7d743b57e2bd",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "월",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "5c996d70-55d4-4345-8d57-a5ad93d6c92f",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "661c4a22-2759-4306-b642-56bef788b6af",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "분기",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"분기 \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "c7e6dfd7-cdcf-40cc-8cbe-8b43fa3f2529",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "일",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "67ffc19d-f501-4430-9f62-75cb60f766d1",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "날짜 계층",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "연도",
                "column": "연도",
                "lineageTag": "4612d4da-045d-469b-a9df-a1d4613cc3ba",
                "ordinal": 0
              },
              {
                "name": "분기",
                "column": "분기",
                "lineageTag": "40248ea4-c78f-4538-81d0-92518088f0bd",
                "ordinal": 1
              },
              {
                "name": "월",
                "column": "월",
                "lineageTag": "faa19211-41b7-484c-8b2e-72a77b5673b7",
                "ordinal": 2
              },
              {
                "name": "일",
                "column": "일",
                "lineageTag": "be476edd-1061-4fb3-b44c-0d2460f440de",
                "ordinal": 3
              }
            ],
            "lineageTag": "c59f67cb-4753-48e3-9b11-efacae2a7287"
          }
        ],
        "isHidden": true,
        "lineageTag": "a0be593d-5291-452d-9378-03091566baed",
        "partitions": [
          {
            "name": "LocalDateTable_f7ac4415-0767-40ca-b482-5f6fde436925",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Data'[퇴사일자])), 1, 1), Date(Year(MAX('Data'[퇴사일자])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "부서및직무정보",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "직무ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "99796933-3442-4093-9c20-28ebecf57c9f",
            "sourceColumn": "직무ID",
            "summarizeBy": "none"
          },
          {
            "name": "positionName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "08853cac-3916-452c-841d-a7ffa89e54c2",
            "sourceColumn": "positionName",
            "summarizeBy": "none"
          },
          {
            "name": "부서ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6466e9b6-2775-4fbb-b889-351ab843d597",
            "sourceColumn": "부서ID",
            "summarizeBy": "none"
          },
          {
            "name": "deptName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7f413aae-f0c6-40a6-ad32-0b7884801871",
            "sourceColumn": "deptName",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "ea7b3b48-b55c-43ce-9923-267e695f62ed",
        "partitions": [
          {
            "name": "부서및직무정보",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    원본 = Excel.Workbook(File.Contents(\"C:\\Users\\havef\\OneDrive - onionbi.co.kr\\_ONIONBI\\02 Training\\01 Personal\\02 Offline\\01 Group\\01_기본반\\02 수업자료_v3.0\\01_직원현황데이터_샘플.xlsx\"), null, true),",
                "    부서및직무정보_Sheet = 원본{[Item=\"부서및직무정보\",Kind=\"Sheet\"]}[Data],",
                "    #\"승격된 헤더\" = Table.PromoteHeaders(부서및직무정보_Sheet, [PromoteAllScalars=true]),",
                "    #\"변경된 유형\" = Table.TransformColumnTypes(#\"승격된 헤더\",{{\"직무ID\", Int64.Type}, {\"직무명\", type text}, {\"부서ID\", Int64.Type}, {\"부서명\", type text}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"변경된 유형\",{{\"부서명\", \"deptName\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}